### ISSUE TITLE
License for your project

### ISSUE THREAD

**Issue by beniroquai** [Kabilan108/WellPlate#1]
Hey @Kabilan108 thanks a lot for sharing this nice piece of code. I was wondering if I may use the 96 wellplate implementation for a project of mine. Thanks a lot! :-) 
It's licensed under GPLv3 (see [Imswitch](https://github.com/kasasxav/ImSwitch)).

**Comment by Kabilan108** [comment]
Certainly! So far, I haven't worked out the controller, but the GUI is pretty much done. I hope you find it useful!

**Comment by beniroquai** [comment]
Yes! Totally useful! :-) 
Thanks!
